version: 1.0.{build}
branches:
  only:
  - CSCore
image: Visual Studio 2017
configuration: Release
platform: x64
build_script:
- cmd: >-
    nuget restore SharpPropoPlus.sln

    msbuild SharpPropoPlus.Decoder.Ppm.Walkera/SharpPropoPlus.Decoder.Ppm.Walkera.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:PreBuildEvent=;PostBuildEvent= 
    appveyor PushArtifact SharpPropoPlus.Decoder.Ppm.Walkera/bin/Release/SharpPropoPlus.Decoder.Ppm.Walkera.dll