version: 1.0.{build}
branches:
  only:
  - CSCore
image: Visual Studio 2017
configuration: Release
platform: x64
build_script:
- cmd: >-
    nuget restore SharpPropoPlus.sln

    msbuild SharpPropoPlus.Decoder.Ppm.Walkera/SharpPropoPlus.Decoder.Ppm.Walkera.csproj /p:PublishDir=Decoders/Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /property:Platform="Any CPU" /p:PreBuildEvent=;PostBuildEvent=

    appveyor PushArtifact Decoders/Release/SharpPropoPlus.Decoder.Ppm.Walkera.dll

    msbuild SharpPropoPlus.Decoder.Ppm.RadioLinkAT9/SharpPropoPlus.Decoder.Ppm.RadioLinkAT9.csproj /p:PublishDir=Decoders/Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /property:Platform="Any CPU" /p:PreBuildEvent=;PostBuildEvent=

    appveyor PushArtifact Decoders/Release/SharpPropoPlus.Decoder.Ppm.RadioLinkAT9.dll